share_document:
    resource: "@ShareBundle/Resources/config/routing/document.yml"
    prefix:   /document

share_homepage:
    path:     /
    defaults: { _controller: ShareBundle:Default:index }

share_language:
    resource: "@ShareBundle/Resources/config/routing/language.yml"
    prefix:   /language

